- name: PLAY-1 Variables
  hosts: localhost
  tasks:
    - name: PLAY-1 and TASK-1
      ansible.builtin.debug:
        msg: "I am learing DevOps with AWS, Instructor is Skanda and During is 100HRS"
        