- name: Variables level from playbook
  hosts: localhost
  vars:
    course: "Devops with AWS"
    Instructor: "Skanda"
    Duration: "100HRS"
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "I am learing the course {{course}}, Trainer is {{Instructor}}, and During is {{Duration}}"
        