- name: Variables from Play level
  hosts: localhost
  vars_files:
  - variables.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: Please enter your name
  #   private: false # User can see the username what we entered
  # - name: WISHES
  #   prompt: Please enter your Wishes
  #   private: false
  # vars:
  #   PERSON: "Skanda from Play"
  #   WISHES: "Morning from Play"
  tasks:
  - name: check variables
    # vars:
    #   PERSON: "Skanda from TASK"
    #   WISHES: "Moring from TASK"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"
      
# This yaml is to see how and which variables will be called first when we give the variables across all places. like, Playbook, file, inventory, task level, prompt variables, command line etc.
