- name: checking data types
  hosts: localhost
  vars:
    NAME: Skanda # Keyvalue pair
    Skills:    # Describes list
    - DevOps
    - Linux
    - AWS
    - Shell
    Experience: # Describes Map
      DevOps: 5
      AWS: 2
      Docker: 1
    Trainer: true
  tasks:
    - name: Print keyvalue pair
      ansible.builtin.debug:
        msg: "name is: {{NAME}}"
    - name: Print Skills
      ansible.builtin.debug:
        msg: "skills: {{Skills}}"
    - name: Print map
      ansible.builtin.debug:
        msg: "Experience is: {{Experience}}"
    - name: Print Boolean
      ansible.builtin.debug:
        msg: "Is he Trainer: {{Trainer}}"

