- name: loops
  hosts: localhost
  tasks:
  - name: print persons
    ansible.builtin.debug:
      msg: "User is {{item}}" # item is a default keyword
    loop:
    - Anil
    - Rama
    - Krishna
    - Sathya